import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapConfig from "./BootstrapConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Blog Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BootstrapConfig/>
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
